name: score-pylint
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repo
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Score nba module with pylint
        run: pylint ./nba/ --disable missing-module-docstring import-error --fail-under=5.0
      - name: Score CLI app with pylint
        run: pylint ./nba/app_cli.py --disable missing-module-docstring import-error --fail-under=5.0
      - name: Score webapp with pylint
        run: pylint ./nba/app_cli.py --disable missing-module-docstring import-error --fail-under=5.0
